# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tripp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tripp

pod 'Alamofire’, '~> 4.7.3'
pod 'AlamofireImage', '~> 3.3.1'
#pod 'RealmSwift', '~> 3.7.5'
pod 'RealmSwift', '~> 3.20.0'
pod 'IQKeyboardManagerSwift', '~> 6.1.1'
pod 'ReachabilitySwift', '~> 4.1.0'
pod 'GoogleMaps', '~> 2.7.0'
pod 'GooglePlaces', '~> 2.7.0'
pod 'AWSS3', '~> 2.4.16'
pod 'NRControls', '~> 2.0.1'
pod 'BWWalkthrough', '~> 2.1.2'
pod 'TTTAttributedLabel', '~> 2.0.0'
pod 'AMPopTip', '~> 3.3.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.44.0'
pod 'Fabric', '~> 1.7.9'
pod 'Crashlytics', '~> 3.10.5'
pod 'Firebase/Core', '~> 5.1.0'

#Facebook
pod 'FBSDKCoreKit', '~> 4.35.0'
pod 'FBSDKLoginKit', '~> 4.35.0'
pod 'FBSDKShareKit', '~> 4.35.0'
pod 'SDWebImage', '~> 4.4.2'

end
